language: java
install: mvn --version
before_script: "./.travis.version_if_tag.sh"
after_success: "./.travis.deploy_if_tag.sh"
sudo: false
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
    secure: "cvL+V1bsmFU3jXE2Hu5AWwRfY4EaONNk2h9ludFQCOpsicTIOE2JhCPSMiMHiNA+1LG0WnlDp/TERO+QwEwBlHBBDZ0ZqDy+lVH9aKARvCO9qynpa6W7WZkzQhN8HKXkzGnqRJvWAvJcIgXNgV8bIwGywaXs0uW+kVAgK47nH14="
    secure: "eTtjY4LTxdm6gGd+hXfNb/ZzSgWwz1+3WIw1G79BB5dd93v6T3EgjO1s/Qb11fjkckXoduMCHYT9fu9qaFwZFh3fXcpFCto0qIMl03nR2w45tubTR7xjADlDvbzvVPflsl58EvHjFEXJO3TiKFxI+yqzPvCvnxeQ2i3xFPttkdI="